export const GET_A_MOVIE_REQUEST = 'GET_A_MOVIE_REQUEST';
export const GET_A_MOVIE_REQUEST_SUCCESS = 'GET_A_MOVIE_REQUEST_SUCCESS';
export const GET_A_MOVIE_REQUEST_FAIL = 'GET_A_MOVIE_REQUEST_FAIL';
