export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_REQUEST_SUCCESS = 'POST_REGISTER_REQUEST_SUCCESS';
export const POST_REGISTER_REQUEST_FAIL = 'POST_REGISTER_REQUEST_FAIL';
export const RESET_ERRORS = 'RESET_ERRORS';
