export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_REQUEST_SUCCESS = 'GET_USER_INFO_REQUEST_SUCCESS';
export const GET_USER_INFO_REQUEST_FAIL = 'GET_USER_INFO_REQUEST_FAIL';
