export const GET_BOOKABLE_SEAT_REQUEST = 'GET_BOOKABLE_SEAT_REQUEST';
export const GET_BOOKABLE_SEAT_REQUEST_SUCCESS =
  'GET_BOOKABLE_SEAT_REQUEST_SUCCESS';
export const GET_BOOKABLE_SEAT_REQUEST_FAIL = 'GET_BOOKABLE_SEAT_REQUEST_FAIL';
