export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_REQUEST_SUCCESS = 'SEARCH_MOVIE_REQUEST_SUCCESS';
export const SEARCH_MOVIE_REQUEST_FAIL = 'SEARCH_MOVIE_REQUEST_FAIL';
export const RESET_DEFAULT = 'RESET_DEFAULT';
